[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
remappings = []

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
gnosis = "${RPC_GNOSIS}"
chiado = "${RPC_CHIADO}"

[etherscan]
#mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}

[fuzz]
runs=2000

# See more config options https://github.com/gakonst/foundry/tree/master/config
